/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jws_aua_Jua */

#ifndef _Included_com_jws_aua_Jua
#define _Included_com_jws_aua_Jua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jws_aua_Jua
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jws_aua_Jua_init
  (JNIEnv *, jclass);

/*
 * Class:     com_jws_aua_Jua
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jws_aua_Jua_free
  (JNIEnv *, jclass);

/*
 * Class:     com_jws_aua_Jua
 * Method:    getOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jws_aua_Jua_getOutput
  (JNIEnv *, jclass);

/*
 * Class:     com_jws_aua_Jua
 * Method:    doString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jws_aua_Jua_doString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jws_aua_Jua
 * Method:    doFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jws_aua_Jua_doFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
